import { PlaidAccount, PlaidTransaction, SpendingInsight } from '@/types/plaid';

// Mock financial data for development
export const mockAccounts: PlaidAccount[] = [
  {
    account_id: 'checking_001',
    balances: {
      available: 8230,
      current: 8230,
      limit: null,
      iso_currency_code: 'USD',
    },
    name: 'Plaid Checking',
    official_name: 'Plaid Gold Standard 0% Interest Checking',
    type: 'depository',
    subtype: 'checking',
    mask: '0000',
  },
  {
    account_id: 'savings_001',
    balances: {
      available: 12345,
      current: 12345,
      limit: null,
      iso_currency_code: 'USD',
    },
    name: 'Plaid Saving',
    official_name: 'Plaid Silver Standard 0.1% Interest Saving',
    type: 'depository',
    subtype: 'savings',
    mask: '1111',
  },
  {
    account_id: 'credit_001',
    balances: {
      available: 4977,
      current: -1023,
      limit: 6000,
      iso_currency_code: 'USD',
    },
    name: 'Plaid Credit Card',
    official_name: 'Plaid Diamond 12.5% APR Interest Credit Card',
    type: 'credit',
    subtype: 'credit card',
    mask: '3333',
  },
  {
    account_id: 'investment_001',
    balances: {
      available: null,
      current: 156789,
      limit: null,
      iso_currency_code: 'USD',
    },
    name: 'Plaid 401k',
    official_name: 'Plaid 401(k) Retirement Account',
    type: 'investment',
    subtype: '401k',
    mask: '4444',
  },
];

export const mockTransactions: PlaidTransaction[] = [
  {
    transaction_id: 'txn_001',
    account_id: 'checking_001',
    amount: -2500,
    date: '2025-06-25',
    name: 'PAYROLL DEPOSIT',
    description: 'Monthly salary deposit from employer',
    category: ['Deposit', 'Payroll'],
    pending: false,
    personal_finance_category: {
      primary: 'INCOME',
      detailed: 'INCOME_WAGES',
    },
  },
  {
    transaction_id: 'txn_002',
    account_id: 'checking_001',
    amount: 1250,
    date: '2025-06-24',
    name: 'RENT PAYMENT',
    description: 'Monthly rent payment to landlord',
    category: ['Payment', 'Rent'],
    pending: false,
    personal_finance_category: {
      primary: 'GENERAL_MERCHANDISE',
      detailed: 'RENT_AND_UTILITIES_RENT',
    },
  },
  {
    transaction_id: 'txn_003',
    account_id: 'checking_001',
    amount: 45.67,
    date: '2025-06-23',
    name: 'WHOLE FOODS MARKET',
    description: 'Grocery shopping at Whole Foods Market',
    merchant_name: 'Whole Foods Market',
    category: ['Shops', 'Food and Drink', 'Groceries'],
    pending: false,
    personal_finance_category: {
      primary: 'FOOD_AND_DRINK',
      detailed: 'FOOD_AND_DRINK_GROCERIES',
    },
  },
  {
    transaction_id: 'txn_004',
    account_id: 'credit_001',
    amount: 89.99,
    date: '2025-06-22',
    name: 'AMAZON.COM',
    description: 'Online purchase from Amazon marketplace',
    merchant_name: 'Amazon',
    category: ['Shops', 'Digital Purchase'],
    pending: false,
    personal_finance_category: {
      primary: 'GENERAL_MERCHANDISE',
      detailed: 'GENERAL_MERCHANDISE_ONLINE_MARKETPLACES',
    },
  },
  {
    transaction_id: 'txn_005',
    account_id: 'checking_001',
    amount: 3.50,
    date: '2025-06-21',
    name: 'STARBUCKS',
    description: 'Coffee purchase at Starbucks',
    merchant_name: 'Starbucks',
    category: ['Food and Drink', 'Restaurants', 'Coffee Shop'],
    pending: false,
    personal_finance_category: {
      primary: 'FOOD_AND_DRINK',
      detailed: 'FOOD_AND_DRINK_COFFEE',
    },
  },
  {
    transaction_id: 'txn_006',
    account_id: 'checking_001',
    amount: 120.00,
    date: '2025-06-20',
    name: 'PG&E ELECTRIC BILL',
    description: 'Monthly electricity utility bill payment',
    category: ['Payment', 'Utilities'],
    pending: false,
    personal_finance_category: {
      primary: 'GENERAL_SERVICES',
      detailed: 'GENERAL_SERVICES_UTILITIES',
    },
  },
  {
    transaction_id: 'txn_007',
    account_id: 'checking_001',
    amount: 25.00,
    date: '2025-06-19',
    name: 'NETFLIX.COM',
    description: 'Monthly Netflix streaming subscription',
    merchant_name: 'Netflix',
    category: ['Service', 'Subscription'],
    pending: false,
    personal_finance_category: {
      primary: 'ENTERTAINMENT',
      detailed: 'ENTERTAINMENT_TV_AND_MOVIES',
    },
  },
  {
    transaction_id: 'txn_008',
    account_id: 'checking_001',
    amount: 67.43,
    date: '2025-06-18',
    name: 'SHELL GAS STATION',
    description: 'Gasoline purchase at Shell gas station',
    merchant_name: 'Shell',
    category: ['Transportation', 'Gas Stations'],
    pending: false,
    personal_finance_category: {
      primary: 'TRANSPORTATION',
      detailed: 'TRANSPORTATION_GAS',
    },
  },
];

export const mockInsights: SpendingInsight[] = [
  {
    id: 'insight_001',
    type: 'spending_spike',
    title: 'Higher than usual spending on groceries',
    description: 'You spent 23% more on groceries this month compared to last month.',
    amount: 156.78,
    category: 'Food and Drink',
    severity: 'info',
    date: '2025-06-26',
  },
  {
    id: 'insight_002',
    type: 'savings_opportunity',
    title: 'Subscription optimization opportunity',
    description: 'You have 3 streaming subscriptions. Consider consolidating to save $15/month.',
    amount: 15,
    severity: 'info',
    date: '2025-06-25',
  },
  {
    id: 'insight_003',
    type: 'budget_exceeded',
    title: 'Transportation budget exceeded',
    description: 'You\'ve exceeded your transportation budget by $45 this month.',
    amount: 45,
    category: 'Transportation',
    severity: 'warning',
    date: '2025-06-24',
  },
];
